#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
#
# disable_builtin_crypto.sh — blacklist built-in kernel crypto modules
#
# DIAGNOSTIC AID FOR TEST ENVIRONMENTS ONLY.
# This script is NOT needed for normal operation of wolfcrypt.ko or crypto2dev.ko.
# wolfcrypt.ko registers at priority 300, which outbids the built-in software
# implementations at their default priorities.  The kernel will select the
# highest-priority registered implementation automatically.
#
# WHY THIS EXISTS:
# In test environments, loaded built-in modules appear as competing candidates
# in /proc/crypto alongside wolfkm entries.  Although the kernel selects the
# wolfkm implementation for new requests (higher priority), the presence of
# the built-in entries can confuse verify_registration.sh's driver-name checks.
# Blacklisting removes that ambiguity so the test output is unambiguous.
#
# WHAT IT DOES:
# Writes /etc/modprobe.d/crypto2dev-override.conf with blacklist directives
# for the kernel's built-in software crypto modules.  Those modules will not
# be auto-loaded after the next reboot (or after they are manually unloaded).
#
# USAGE:
#   sudo ./scripts/disable_builtin_crypto.sh           # write blacklist
#   sudo ./scripts/disable_builtin_crypto.sh --restore # remove blacklist
#
# Both operations are idempotent.
#
# Run as root with wolfcrypt.ko loaded:
#   sudo insmod wolfcrypt.ko
#   sudo ./scripts/disable_builtin_crypto.sh
#   # reboot, or manually unload modules listed below
#   sudo ./scripts/verify_registration.sh

set -euo pipefail

CONF_FILE="/etc/modprobe.d/crypto2dev-override.conf"

# ANSI color codes (suppressed when not a terminal)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' NC=''
fi

die() {
    echo -e "${RED}ERROR${NC}: $*" >&2
    exit 1
}

require_root() {
    if [[ $EUID -ne 0 ]]; then
        die "this script must be run as root (sudo $0 $*)"
    fi
}

#
# Modules to blacklist — the kernel's built-in software crypto implementations.
#
# wolfcrypt.ko registers competing implementations at priority 300, which
# outbids these modules' default priorities.  Blacklisting them ensures they
# are never loaded in test environments so /proc/crypto shows only wolfkm
# entries for the covered algorithms.
#
# Each entry is:  MODULE_NAME  REASON
# (REASON is written into the conf file as a comment for operator clarity.)
#
declare -a MODULES=(
    "aes-generic"             "software AES, no hardware acceleration (priority ~100)"
    "aes-x86_64"              "x86 AES software fallback (priority ~200)"
    "ghash-clmulni-intel"     "GHASH via CLMUL instruction, used by gcm(aes)"
    "sha256-generic"          "software SHA-256 (priority ~100)"
    "sha384-generic"          "software SHA-384 (priority ~100)"
    "sha512-generic"          "software SHA-384/512 (priority ~100)"
    "sha3-256-generic"        "software SHA3-256 (priority ~100)"
    "sha3-512-generic"        "software SHA3-512 (priority ~100)"
    "hmac"                    "generic HMAC wrapper module"
    "cmac"                    "generic CMAC wrapper module"
    "ccm"                     "generic CCM mode implementation"
    "gcm"                     "generic GCM mode implementation"
)

# MODULES is stored as a flat array of pairs: name, reason, name, reason, ...
# Extract just the module names for iteration.
module_names() {
    local i
    for (( i=0; i<${#MODULES[@]}; i+=2 )); do
        echo "${MODULES[$i]}"
    done
}

do_install() {
    echo -e "${YELLOW}WARNING${NC}: This is a diagnostic aid for test environments only."
    echo "         It is NOT needed for normal production operation."
    echo ""
    echo "Writing ${CONF_FILE} ..."
    echo ""

    # Build the conf file content.  Always overwrite (idempotent).
    {
        echo "# crypto2dev-override.conf"
        echo "# SPDX-License-Identifier: GPL-2.0-only"
        echo "#"
        echo "# Blacklist built-in kernel software crypto modules so that wolfcrypt.ko's"
        echo "# priority-300 registrations are the only contenders in /proc/crypto."
        echo "#"
        echo "# DIAGNOSTIC AID — NOT needed for normal operation."
        echo "# Generated by: $0"
        echo "# Generated on: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        echo "# Remove with:  $0 --restore"
        echo ""

        local i
        for (( i=0; i<${#MODULES[@]}; i+=2 )); do
            local mod="${MODULES[$i]}"
            local reason="${MODULES[$i+1]}"
            echo "# ${reason}"
            echo "blacklist ${mod}"
            echo ""
        done
    } > "${CONF_FILE}"

    echo "Wrote ${CONF_FILE}:"
    echo ""
    # Show exactly what was written (indent for clarity)
    sed 's/^/  /' "${CONF_FILE}"
    echo ""

    # Attempt to unload currently-loaded blacklisted modules from the running
    # kernel.  modprobe -r is best-effort: a module in use will refuse to
    # unload, which is fine — the blacklist takes effect on next load attempt.
    echo "Attempting to unload currently-loaded blacklisted modules ..."
    local unloaded=0
    local skipped=0
    while IFS= read -r mod; do
        # Normalise: kernel shows module names with underscores, modprobe
        # accepts hyphens.  Check /sys/module with underscores.
        local sys_name
        sys_name="${mod//-/_}"
        if [[ -d "/sys/module/${sys_name}" ]]; then
            if modprobe -r "${mod}" 2>/dev/null; then
                echo -e "  ${GREEN}unloaded${NC}  ${mod}"
                (( unloaded++ )) || true
            else
                echo -e "  ${YELLOW}in use${NC}   ${mod} — will take effect after reboot"
                (( skipped++ )) || true
            fi
        else
            echo "  not loaded  ${mod}"
        fi
    done < <(module_names)

    echo ""
    if [[ $skipped -gt 0 ]]; then
        echo -e "${YELLOW}NOTE${NC}: ${skipped} module(s) could not be unloaded (in use)."
        echo "      Reboot to fully apply the blacklist."
    else
        echo -e "${GREEN}Done${NC}: blacklist written and all listed modules unloaded."
        echo "      Run sudo ./scripts/verify_registration.sh to confirm."
    fi
}

do_restore() {
    if [[ ! -f "${CONF_FILE}" ]]; then
        echo "Nothing to restore: ${CONF_FILE} does not exist."
        exit 0
    fi

    echo "Removing ${CONF_FILE} ..."
    rm -f "${CONF_FILE}"
    echo -e "${GREEN}Done${NC}: ${CONF_FILE} removed."
    echo ""
    echo "Built-in crypto modules will be auto-loaded again as needed."
    echo "A reboot (or manual modprobe) is required to reload them now."
}

usage() {
    echo "Usage: sudo $0 [--restore]"
    echo ""
    echo "  (no flags)   Write blacklist to ${CONF_FILE}"
    echo "  --restore    Remove the blacklist file"
    echo ""
    echo "This is a DIAGNOSTIC AID for test environments only."
    echo "It is NOT needed for normal operation of wolfcrypt.ko or crypto2dev.ko."
    exit 1
}

# Parse arguments
case "${1:-}" in
    "")
        require_root "$@"
        do_install
        ;;
    --restore)
        require_root "$@"
        do_restore
        ;;
    -h|--help)
        usage
        ;;
    *)
        die "unknown argument: $1"
        ;;
esac
