// SPDX-License-Identifier: GPL-2.0-only
/*
 * test_kpp.c — kernel module: ECDH P-256 known-answer tests
 *
 * Tests wolfcrypt.ko's ECDH registration via the kernel KPP API.
 * Algorithm names are curve-specific: "ecdh-nist-p256", "ecdh-nist-p384".
 * struct ecdh has only .key and .key_size; curve is in the algorithm name.
 *
 * Tests:
 *   1. ECDH P-256: compute ECDH(A_priv, B_pub) and compare to known shared
 *      secret from tests/vectors/ecdh.h (generated by OpenSSL 3.0.13).
 *   2. ECDH P-384: if HAVE_ECDH_P384_VECTORS is defined (requires
 *      tests/vectors/ecdh_p384.h).
 *
 * Peer public key for kpp_request_set_input: raw uncompressed EC point
 * (04 || X || Y), 65 bytes for P-256 or 97 bytes for P-384.
 *
 * Private key is passed via crypto_kpp_set_secret with a serialized
 * struct ecdh (from include/crypto/ecdh.h).
 *
 * Load:
 *   insmod test_kpp.ko
 *   dmesg | grep test_kpp
 *
 * Requires wolfcrypt.ko to be loaded before insmod.
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/slab.h>
#include <linux/string.h>
#include <linux/scatterlist.h>
#include <crypto/kpp.h>
#include <crypto/ecdh.h>

#include "../vectors/ecdh.h"
#define HAVE_ECDH_P384_VECTORS
#include "../vectors/ecdh_p384.h"

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("crypto2dev KPP (ECDH) known-answer tests");
MODULE_AUTHOR("wolfSSL Inc.");

static int test_pass;
static int test_fail;

#define T_PASS(fmt, ...) do {                                                  \
	pr_info("test_kpp: PASS " fmt "\n", ##__VA_ARGS__);                   \
	test_pass++;                                                          \
} while (0)

#define T_FAIL(fmt, ...) do {                                                  \
	pr_err("test_kpp: FAIL " fmt "\n", ##__VA_ARGS__);                    \
	test_fail++;                                                          \
} while (0)

/* ── Shared helper: compute ECDH shared secret ──────────────────────────── */
/*
 * ecdh_compute_shared - run ECDH with a known private key and peer public key.
 *
 * @algo:          kernel kpp algorithm name, e.g. "ecdh-nist-p256"
 * @raw_priv:      raw private key bytes (big-endian scalar)
 * @raw_priv_len:  length of raw_priv (32 for P-256, 48 for P-384)
 * @peer_pub:      raw uncompressed peer public key (04||x||y)
 * @peer_pub_len:  length of peer_pub (65 for P-256, 97 for P-384)
 * @result:        output buffer (raw_priv_len bytes for x-coordinate)
 *
 * Returns 0 on success, negative errno on failure.
 */
static int ecdh_compute_shared(const char *algo,
				const u8 *raw_priv, unsigned int raw_priv_len,
				const u8 *peer_pub, unsigned int peer_pub_len,
				u8 *result)
{
	struct crypto_kpp *tfm;
	struct kpp_request *req;
	struct ecdh params;
	struct scatterlist src_sg, dst_sg;
	unsigned int params_buf_len;
	u8 *params_buf;
	int ret;

	tfm = crypto_alloc_kpp(algo, 0, 0);
	if (IS_ERR(tfm))
		return PTR_ERR(tfm);

	memset(&params, 0, sizeof(params));
	/* struct ecdh on kernel 6.x: only .key and .key_size; curve is in algo */
	params.key      = (char *)raw_priv; /* encode_key reads; does not modify */
	params.key_size = (unsigned short)raw_priv_len;

	params_buf_len = crypto_ecdh_key_len(&params);
	params_buf = kmalloc(params_buf_len, GFP_KERNEL);
	if (!params_buf) {
		ret = -ENOMEM;
		goto out_free_tfm;
	}

	ret = crypto_ecdh_encode_key((char *)params_buf, params_buf_len, &params);
	if (ret)
		goto out_free_params;

	ret = crypto_kpp_set_secret(tfm, params_buf, params_buf_len);
	if (ret)
		goto out_free_params;

	req = kpp_request_alloc(tfm, GFP_KERNEL);
	if (!req) {
		ret = -ENOMEM;
		goto out_free_params;
	}

	sg_init_one(&src_sg, peer_pub, peer_pub_len);
	sg_init_one(&dst_sg, result,   raw_priv_len);
	kpp_request_set_input(req,  &src_sg, peer_pub_len);
	kpp_request_set_output(req, &dst_sg, raw_priv_len);

	ret = crypto_kpp_compute_shared_secret(req);

	kpp_request_free(req);
out_free_params:
	memzero_explicit(params_buf, params_buf_len);
	kfree(params_buf);
out_free_tfm:
	crypto_free_kpp(tfm);
	return ret;
}

/* ── Test 1: ECDH P-256 known-answer ────────────────────────────────────── */
/*
 * Compute ECDH(A_priv, B_pub) and compare to ecdh_shared_secret.
 *
 * Vectors from tests/vectors/ecdh.h:
 *   Party A private key (raw 32 bytes): ecdh_a_raw_priv
 *   Party B public key  (raw 65 bytes): ecdh_b_raw_pub  (04||x||y)
 *   Expected shared secret (32 bytes):  ecdh_shared_secret (x-coordinate)
 *
 * Source: openssl pkeyutl -derive -inkey ec_a_priv.pem -peerkey ec_b_pub.pem
 * Verified: ECDH(A,B) == ECDH(B,A) confirmed with cmp(1).
 */
static void ecdh_test_p256(void)
{
	u8 result[32];
	int ret;

	memset(result, 0, sizeof(result));

	ret = ecdh_compute_shared(
		"ecdh-nist-p256",
		ecdh_a_raw_priv, sizeof(ecdh_a_raw_priv),
		ecdh_b_raw_pub,  sizeof(ecdh_b_raw_pub),
		result);

	if (ret) {
		T_FAIL("ECDH P-256: compute_shared_secret failed: %d", ret);
		goto out;
	}

	if (memcmp(result, ecdh_shared_secret, sizeof(ecdh_shared_secret)) != 0) {
		T_FAIL("ECDH P-256: shared secret mismatch");
		goto out;
	}

	T_PASS("ECDH P-256 shared secret matches known vector");

out:
	memzero_explicit(result, sizeof(result));
}

/* ── Test 2: ECDH P-384 known-answer (requires ecdh_p384.h) ─────────────── */
#ifdef HAVE_ECDH_P384_VECTORS
static void ecdh_test_p384(void)
{
	u8 result[48];
	int ret;

	memset(result, 0, sizeof(result));

	ret = ecdh_compute_shared(
		"ecdh-nist-p384",
		ecdh_p384_a_raw_priv, sizeof(ecdh_p384_a_raw_priv),
		ecdh_p384_b_raw_pub,  sizeof(ecdh_p384_b_raw_pub),
		result);

	if (ret) {
		T_FAIL("ECDH P-384: compute_shared_secret failed: %d", ret);
		goto out;
	}

	if (memcmp(result, ecdh_p384_shared_secret,
		   sizeof(ecdh_p384_shared_secret)) != 0) {
		T_FAIL("ECDH P-384: shared secret mismatch");
		goto out;
	}

	T_PASS("ECDH P-384 shared secret matches known vector");

out:
	memzero_explicit(result, sizeof(result));
}
#endif /* HAVE_ECDH_P384_VECTORS */

/* ── Module init/exit ───────────────────────────────────────────────────── */

static int __init test_kpp_init(void)
{
	struct crypto_kpp *probe;

	probe = crypto_alloc_kpp("ecdh-nist-p256", 0, 0);
	if (!IS_ERR(probe)) {
		pr_info("test_kpp: NOTE ecdh-nist-p256 driver: %s\n",
			crypto_tfm_alg_driver_name(crypto_kpp_tfm(probe)));
		crypto_free_kpp(probe);
	}

	ecdh_test_p256();
#ifdef HAVE_ECDH_P384_VECTORS
	ecdh_test_p384();
#endif

	if (test_fail == 0)
		pr_info("test_kpp: ALL TESTS PASSED (%d/%d)\n",
			test_pass, test_pass + test_fail);
	else
		pr_err("test_kpp: TESTS FAILED (%d failed, %d passed)\n",
		       test_fail, test_pass);

	/* Return 0 even on test failure so dmesg can be inspected.
	 * CI scripts check for "FAIL" in dmesg rather than insmod exit code. */
	return 0;
}

static void __exit test_kpp_exit(void)
{
}

module_init(test_kpp_init);
module_exit(test_kpp_exit);
