// SPDX-License-Identifier: GPL-2.0-only
/*
 * test_akcipher.c — kernel module: RSA-2048 known-answer tests
 *
 * Tests wolfcrypt.ko's RSA registration via the kernel crypto APIs.
 *
 * On kernel 6.5+, PKCS#1 sign/verify use the "sig" type (crypto_sig API).
 * Raw RSA encrypt/decrypt still use the "akcipher" type (crypto_akcipher API).
 *
 * Tests:
 *   1. Sign known digest with private key; compare to known PKCS#1 v1.5
 *      signature from rsa.h (generated by OpenSSL 3.0.13).
 *   2. Verify known signature with public key; expect 0 (success).
 *   3. Verify tampered signature (one byte flipped); expect error.
 *   4. Encrypt a known plaintext with public key, decrypt with private key;
 *      verify round-trip (integration test — tests #1/#2 are the KAT oracle).
 *   5. Verify crypto_sig_maxsize returns rsa2048_key_bytes (256).
 *
 * Load:
 *   insmod test_akcipher.ko
 *   dmesg | grep test_akcipher
 *
 * Requires wolfcrypt.ko to be loaded before insmod.
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/version.h>

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("crypto2dev RSA akcipher/sig known-answer tests");
MODULE_AUTHOR("wolfSSL Inc.");

/*
 * crypto/sig.h was added in kernel 6.2.  On older kernels this module
 * builds as an empty stub; CI excludes it via SKIP_MODULES anyway.
 */
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0)

#include <linux/slab.h>
#include <linux/string.h>
#include <linux/scatterlist.h>
#include <crypto/akcipher.h>
#include <crypto/sig.h>

#include "../vectors/rsa.h"

/*
 * PKCS#1 v1.5 sign/verify: type "sig" on kernel 6.5+.
 * /proc/crypto shows: "pkcs1(rsa,sha256)" with type=sig.
 */
#define SIG_ALGO    "pkcs1(rsa,sha256)"
/* Raw RSA for encrypt/decrypt: still type "akcipher" */
#define RSA_ALGO    "rsa"

#define DIGEST_LEN   32    /* SHA-256 */
#define SIG_LEN      256   /* RSA-2048 */

static int test_pass;
static int test_fail;

#define T_PASS(fmt, ...) do {                                                  \
	pr_info("test_akcipher: PASS " fmt "\n", ##__VA_ARGS__);              \
	test_pass++;                                                          \
} while (0)

#define T_FAIL(fmt, ...) do {                                                  \
	pr_err("test_akcipher: FAIL " fmt "\n", ##__VA_ARGS__);              \
	test_fail++;                                                          \
} while (0)

/* ── Test 1: sign known digest, compare to known signature ─────────────── */
/*
 * PKCS#1 v1.5 sign via crypto_sig API:
 *   src = SHA-256 digest (32 bytes)
 *   dst = PKCS#1 v1.5 signature (256 bytes)
 *   Returns: bytes written (256) on success, negative errno on failure.
 *
 * Private key: PKCS#1 RSAPrivateKey DER at rsa2048_priv_der[26..].
 */
static void rsa_test_sign_kat(void)
{
	struct crypto_sig *tfm;
	u8 *sig;
	int ret;

	sig = kmalloc(SIG_LEN, GFP_KERNEL);
	if (!sig) {
		T_FAIL("sign KAT: kmalloc failed");
		return;
	}

	tfm = crypto_alloc_sig(SIG_ALGO, 0, 0);
	if (IS_ERR(tfm)) {
		T_FAIL("sign KAT: crypto_alloc_sig failed: %ld", PTR_ERR(tfm));
		kfree(sig);
		return;
	}

	ret = crypto_sig_set_privkey(
		tfm,
		rsa2048_priv_der + RSA2048_PKCS1_PRIV_OFFSET,
		RSA2048_PKCS1_PRIV_LEN);
	if (ret) {
		T_FAIL("sign KAT: set_privkey failed: %d", ret);
		goto out;
	}

	ret = crypto_sig_sign(tfm,
			      rsa2048_test_digest, DIGEST_LEN,
			      sig, SIG_LEN);
	if (ret < 0) {
		T_FAIL("sign KAT: sign failed: %d", ret);
		goto out;
	}
	if (ret != SIG_LEN) {
		T_FAIL("sign KAT: unexpected sig len %d (expected %d)", ret, SIG_LEN);
		goto out;
	}

	if (memcmp(sig, rsa2048_test_sig, SIG_LEN) != 0) {
		T_FAIL("sign KAT: signature mismatch");
		goto out;
	}

	T_PASS("pkcs1(rsa,sha256) sign matches known vector");

out:
	crypto_free_sig(tfm);
	memzero_explicit(sig, SIG_LEN);
	kfree(sig);
}

/* ── Test 2: verify known signature with public key ─────────────────────── */
/*
 * PKCS#1 v1.5 verify via crypto_sig API:
 *   src = signature (256 bytes)
 *   digest = SHA-256 digest (32 bytes)
 *   Returns: 0 on success, negative errno on failure.
 *
 * Public key: SubjectPublicKeyInfo DER (rsa2048_pub_der, 294 bytes).
 */
static void rsa_test_verify_kat(void)
{
	struct crypto_sig *tfm;
	int ret;

	tfm = crypto_alloc_sig(SIG_ALGO, 0, 0);
	if (IS_ERR(tfm)) {
		T_FAIL("verify KAT: crypto_alloc_sig failed: %ld", PTR_ERR(tfm));
		return;
	}

	ret = crypto_sig_set_pubkey(tfm, rsa2048_pub_der, rsa2048_pub_der_len);
	if (ret) {
		T_FAIL("verify KAT: set_pubkey failed: %d", ret);
		goto out;
	}

	ret = crypto_sig_verify(tfm,
				rsa2048_test_sig,    SIG_LEN,
				rsa2048_test_digest, DIGEST_LEN);
	if (ret) {
		T_FAIL("verify KAT: verify returned %d (expected 0)", ret);
		goto out;
	}

	T_PASS("pkcs1(rsa,sha256) verify known signature");

out:
	crypto_free_sig(tfm);
}

/* ── Test 3: verify tampered signature — must fail ──────────────────────── */
static void rsa_test_verify_tampered(void)
{
	struct crypto_sig *tfm;
	u8 tampered_sig[SIG_LEN];
	int ret;

	memcpy(tampered_sig, rsa2048_test_sig, SIG_LEN);
	/* Flip one byte in the middle of the signature */
	tampered_sig[SIG_LEN / 2] ^= 0xFF;

	tfm = crypto_alloc_sig(SIG_ALGO, 0, 0);
	if (IS_ERR(tfm)) {
		T_FAIL("verify tampered: crypto_alloc_sig failed: %ld",
		       PTR_ERR(tfm));
		return;
	}

	ret = crypto_sig_set_pubkey(tfm, rsa2048_pub_der, rsa2048_pub_der_len);
	if (ret) {
		T_FAIL("verify tampered: set_pubkey failed: %d", ret);
		goto out;
	}

	ret = crypto_sig_verify(tfm,
				tampered_sig,        SIG_LEN,
				rsa2048_test_digest, DIGEST_LEN);
	if (ret == 0) {
		T_FAIL("verify tampered: accepted corrupted signature");
	} else {
		T_PASS("pkcs1(rsa,sha256) rejected tampered signature (%d)", ret);
	}

out:
	crypto_free_sig(tfm);
	memzero_explicit(tampered_sig, sizeof(tampered_sig));
}

/* ── Test 4: encrypt + decrypt round-trip (raw RSA akcipher) ────────────── */
/*
 * Integration test using the "rsa" akcipher (still type akcipher on 6.17).
 * Encrypts with public key, decrypts with private key, verifies round-trip.
 *
 * This is NOT a known-answer test — tests #1 and #2 are the correctness oracle.
 * This test verifies that the raw RSA API is wired up and round-trips correctly.
 *
 * Plaintext: 256-byte buffer [0x00, 0x01, ..., 0xFF].
 * First byte 0x00 ensures the integer value < n (RSA-2048 modulus).
 */
static void rsa_test_roundtrip(void)
{
	struct crypto_akcipher *tfm_pub, *tfm_priv;
	struct akcipher_request *req;
	struct scatterlist src, dst;
	u8 *plaintext, *ciphertext, *recovered;
	unsigned int i;
	int ret;

	plaintext  = kmalloc(SIG_LEN, GFP_KERNEL);
	ciphertext = kmalloc(SIG_LEN, GFP_KERNEL);
	recovered  = kmalloc(SIG_LEN, GFP_KERNEL);
	if (!plaintext || !ciphertext || !recovered) {
		T_FAIL("roundtrip: kmalloc failed");
		goto out_free;
	}

	for (i = 0; i < SIG_LEN; i++)
		plaintext[i] = (u8)i;

	/* ── Encrypt with public key ──────────────────────────────────────── */

	tfm_pub = crypto_alloc_akcipher(RSA_ALGO, 0, 0);
	if (IS_ERR(tfm_pub)) {
		T_FAIL("roundtrip: alloc(pub) failed: %ld", PTR_ERR(tfm_pub));
		tfm_pub = NULL;
		goto out_free;
	}

	ret = crypto_akcipher_set_pub_key(
		tfm_pub, rsa2048_pub_der, rsa2048_pub_der_len);
	if (ret) {
		T_FAIL("roundtrip: set_pub_key failed: %d", ret);
		goto out_free_pub;
	}

	req = akcipher_request_alloc(tfm_pub, GFP_KERNEL);
	if (!req) {
		T_FAIL("roundtrip: request_alloc(pub) failed");
		goto out_free_pub;
	}

	sg_init_one(&src, plaintext,  SIG_LEN);
	sg_init_one(&dst, ciphertext, SIG_LEN);
	akcipher_request_set_crypt(req, &src, &dst, SIG_LEN, SIG_LEN);

	ret = crypto_akcipher_encrypt(req);
	akcipher_request_free(req);
	if (ret) {
		T_FAIL("roundtrip: encrypt failed: %d", ret);
		goto out_free_pub;
	}

	/* ── Decrypt with private key ─────────────────────────────────────── */

	tfm_priv = crypto_alloc_akcipher(RSA_ALGO, 0, 0);
	if (IS_ERR(tfm_priv)) {
		T_FAIL("roundtrip: alloc(priv) failed: %ld", PTR_ERR(tfm_priv));
		tfm_priv = NULL;
		goto out_free_pub;
	}

	ret = crypto_akcipher_set_priv_key(
		tfm_priv,
		rsa2048_priv_der + RSA2048_PKCS1_PRIV_OFFSET,
		RSA2048_PKCS1_PRIV_LEN);
	if (ret) {
		T_FAIL("roundtrip: set_priv_key failed: %d", ret);
		goto out_free_priv;
	}

	req = akcipher_request_alloc(tfm_priv, GFP_KERNEL);
	if (!req) {
		T_FAIL("roundtrip: request_alloc(priv) failed");
		goto out_free_priv;
	}

	sg_init_one(&src, ciphertext, SIG_LEN);
	sg_init_one(&dst, recovered,  SIG_LEN);
	akcipher_request_set_crypt(req, &src, &dst, SIG_LEN, SIG_LEN);

	ret = crypto_akcipher_decrypt(req);
	akcipher_request_free(req);
	if (ret) {
		T_FAIL("roundtrip: decrypt failed: %d", ret);
		goto out_free_priv;
	}

	if (memcmp(recovered, plaintext, SIG_LEN) != 0) {
		T_FAIL("roundtrip: decrypted plaintext mismatch");
		goto out_free_priv;
	}

	T_PASS("rsa encrypt+decrypt round-trip");

out_free_priv:
	crypto_free_akcipher(tfm_priv);
out_free_pub:
	crypto_free_akcipher(tfm_pub);
out_free:
	if (recovered) {
		memzero_explicit(recovered,  SIG_LEN);
		kfree(recovered);
	}
	if (ciphertext) {
		memzero_explicit(ciphertext, SIG_LEN);
		kfree(ciphertext);
	}
	if (plaintext) {
		memzero_explicit(plaintext,  SIG_LEN);
		kfree(plaintext);
	}
}

/* ── Test 5: max_size check ─────────────────────────────────────────────── */
static void rsa_test_maxsize(void)
{
	struct crypto_sig *tfm;
	unsigned int maxsz;
	int ret;

	tfm = crypto_alloc_sig(SIG_ALGO, 0, 0);
	if (IS_ERR(tfm)) {
		T_FAIL("maxsize: crypto_alloc_sig failed: %ld", PTR_ERR(tfm));
		return;
	}

	ret = crypto_sig_set_pubkey(tfm, rsa2048_pub_der, rsa2048_pub_der_len);
	if (ret) {
		T_FAIL("maxsize: set_pubkey failed: %d", ret);
		goto out;
	}

	maxsz = crypto_sig_maxsize(tfm);
	if (maxsz != rsa2048_key_bytes) {
		T_FAIL("maxsize: got %u, expected %u", maxsz, rsa2048_key_bytes);
	} else {
		T_PASS("pkcs1(rsa,sha256) maxsize == %u", rsa2048_key_bytes);
	}

out:
	crypto_free_sig(tfm);
}

/* ── Module init/exit ───────────────────────────────────────────────────── */

static int __init test_akcipher_init(void)
{
	struct crypto_sig *probe;

	probe = crypto_alloc_sig(SIG_ALGO, 0, 0);
	if (!IS_ERR(probe)) {
		pr_info("test_akcipher: NOTE %s driver: %s\n",
			SIG_ALGO,
			crypto_tfm_alg_driver_name(crypto_sig_tfm(probe)));
		crypto_free_sig(probe);
	}

	rsa_test_sign_kat();
	rsa_test_verify_kat();
	rsa_test_verify_tampered();
	rsa_test_roundtrip();
	rsa_test_maxsize();

	if (test_fail == 0)
		pr_info("test_akcipher: ALL TESTS PASSED (%d/%d)\n",
			test_pass, test_pass + test_fail);
	else
		pr_err("test_akcipher: TESTS FAILED (%d failed, %d passed)\n",
		       test_fail, test_pass);

	/* Return 0 even on test failure so dmesg can be inspected.
	 * CI scripts check for "FAIL" in dmesg rather than insmod exit code. */
	return 0;
}

static void __exit test_akcipher_exit(void)
{
}

module_init(test_akcipher_init);
module_exit(test_akcipher_exit);

#else /* LINUX_VERSION_CODE < KERNEL_VERSION(6, 2, 0) */

static int __init test_akcipher_init(void)
{
	pr_info("test_akcipher: skipped — crypto/sig.h requires kernel >= 6.2\n");
	return 0;
}
static void __exit test_akcipher_exit(void) {}
module_init(test_akcipher_init);
module_exit(test_akcipher_exit);

#endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0) */
